// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHZ0NL84m-tzH-vX1qNdjdujjuYO_dgic',
    appId: '1:812307841842:web:61e4a43b7940a1a1574d2b',
    messagingSenderId: '812307841842',
    projectId: 'monitoringapp-7730e',
    authDomain: 'monitoringapp-7730e.firebaseapp.com',
    databaseURL: 'https://monitoringapp-7730e-default-rtdb.firebaseio.com',
    storageBucket: 'monitoringapp-7730e.firebasestorage.app',
    measurementId: 'G-JLVNY4CYR4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1VetvHi36cORYoPtaw1WHlcJenft1qjQ',
    appId: '1:812307841842:android:90a07a048b2d0e2e574d2b',
    messagingSenderId: '812307841842',
    projectId: 'monitoringapp-7730e',
    databaseURL: 'https://monitoringapp-7730e-default-rtdb.firebaseio.com',
    storageBucket: 'monitoringapp-7730e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGsW3sV1R6Q7-RpUCxahkfkuFyqAwNRws',
    appId: '1:812307841842:ios:a50cbfc5a17a0786574d2b',
    messagingSenderId: '812307841842',
    projectId: 'monitoringapp-7730e',
    databaseURL: 'https://monitoringapp-7730e-default-rtdb.firebaseio.com',
    storageBucket: 'monitoringapp-7730e.firebasestorage.app',
    iosBundleId: 'com.example.monitoringApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGsW3sV1R6Q7-RpUCxahkfkuFyqAwNRws',
    appId: '1:812307841842:ios:a50cbfc5a17a0786574d2b',
    messagingSenderId: '812307841842',
    projectId: 'monitoringapp-7730e',
    databaseURL: 'https://monitoringapp-7730e-default-rtdb.firebaseio.com',
    storageBucket: 'monitoringapp-7730e.firebasestorage.app',
    iosBundleId: 'com.example.monitoringApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHZ0NL84m-tzH-vX1qNdjdujjuYO_dgic',
    appId: '1:812307841842:web:42d70462b546700a574d2b',
    messagingSenderId: '812307841842',
    projectId: 'monitoringapp-7730e',
    authDomain: 'monitoringapp-7730e.firebaseapp.com',
    databaseURL: 'https://monitoringapp-7730e-default-rtdb.firebaseio.com',
    storageBucket: 'monitoringapp-7730e.firebasestorage.app',
    measurementId: 'G-JMZ4R3MTS9',
  );
}
